[package]
name = "rmk"
version = "0.0.5"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
readme = "../README.md"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = { version = "0.2.7", features = ["unproven"] }
embedded-storage = { version = "0.3" }
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
num_enum = { version = "0.7.0", default-features = false }
log = "0.4.19"
rtic-monotonics = { version = "1.0.0", features = ["cortex-m-systick"] }
usb-device = "0.2.9"
usbd-hid = "0.6.1"
packed_struct = { version = "0.10.1", default-features = false }
byteorder = { version = "1.4", default-features = false }
embedded-alloc = "0.5.0"

[features]
default = ["col2row"]
col2row = []
eeprom = []
