[package]
name = "rmk-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8"
serde = "1.0"
serde_derive = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
rmk-config = { path = "../rmk-config" }
prettyplease = "0.2"

[lib]
proc-macro = true
