[package]
name = "rmk-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmk-macro = { path = "../rmk-macro" }
rmk-config = { path = "../rmk-config" }
embedded-hal = "1.0"