cargo-features = ["per-package-target"]

[package]
name = "rmk-stm32h7"
version = "0.0.2"
description = ""
edition = "2021"
license = "Apache-2.0"
forced-target = "thumbv7em-none-eabihf"

[dependencies]
rmk = { version = "0.0.3", path = "../../rmk", features = [
    "eeprom",
    "col2row",
] }
stm32h7xx-hal = { version = "0.14.0", features = [
    "stm32h7b0",
    "rt",
    "log-rtt",
    "usb_hs",
] }
# Workspace dependencies
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
rtt-target = "0.4.0"
log = "0.4.19"
rtic = { version = "2.0.1", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "1.0.0", features = ["cortex-m-systick"] }
usb-device = "0.2.9"
usbd-hid = "0.6.1"
packed_struct = { version = "0.10.1", default-features = false }
embedded-storage = { version = "0.3" }
