name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Install target
      run: rustup target add thumbv7em-none-eabihf thumbv6m-none-eabi
    - name: Build
      run: cargo build -p rmk --verbose
    - name: Build rp2040
      working-directory: ./boards/rp2040
      run: cargo build --verbose
    - name: Build stm32h7
      working-directory: ./boards/stm32h7
      run: cargo build --verbose
